# Generated by Django 4.0 on 2022-01-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211220_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
